### ISSUE TITLE
SendNotFoundAsync returns Error: aborted instead of 404: Version 5.1.0

### ISSUE THREAD

**Issue by Miatrix** [FastEndpoints/FastEndpoints#267]
I created a new .net core 6 API project.  Created the following endpoint as a test:

```
[HttpGet("/weatherforecast"), AllowAnonymous]
public class WeatherForecastEndpoint : EndpointWithoutRequest<WeatherForecast[]>
{
    public override async Task HandleAsync(CancellationToken ct)
    {
        var summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };


        var result = Enumerable.Range(1, 5).Select(index =>
                new WeatherForecast
                (
                    DateTime.Now.AddDays(index),
                    Random.Shared.Next(-20, 55),
                    summaries[Random.Shared.Next(summaries.Length)]
                ))
            .ToArray();

        //await SendOkAsync(result, ct);
        await SendNotFoundAsync(ct);
    }
}
```

Error Message: 
```
An unhandled exception has occurred while executing the request.
      System.ArgumentException: Type is not supported.
         at System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(Type type)
         at FastEndpoints.Endpoint`2.InitResponseDTO()
         at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
warn: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[2]
      The response has already started, the error page middleware will not be executed.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HML2DJ0V3C4L", Request id "0HML2DJ0V3C4L:00000002": An unhandled exception was thrown by the application.
      System.ArgumentException: Type is not supported.
         at System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(Type type)
         at FastEndpoints.Endpoint`2.InitResponseDTO()
         at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

Using:
await SendAsync(Array.Empty<WeatherForecast>(), 404, ct); 

will return a 404, however it also returns [] as part of the response.

I would expect SendNotFoundAsync(ct) to return an empty 404 like  return Results.NotFound(); does in the minimal api code.

**Comment by dj-nitehawk** [comment]
pls try the latest beta `v5.2.0-beta21`
the following works in the beta:
```cs
public class Model
{
    public string Name { get; set; }
}

[HttpGet("/weatherforecast"), AllowAnonymous]
public class WeatherForecastEndpoint : EndpointWithoutRequest<Model[]>
{
    public override async Task HandleAsync(CancellationToken ct)
    {
        await SendOkAsync(Array.Empty<Model>());
    }
}
```

**Comment by Miatrix** [comment]
If you change the return type to string you still get the error even with beta-21

**Comment by dj-nitehawk** [comment]
this also works:
```cs
[HttpGet("/weatherforecast"), AllowAnonymous]
public class WeatherForecastEndpoint : EndpointWithoutRequest<string[]>
{
    public override async Task HandleAsync(CancellationToken ct)
    {
        await SendOkAsync(Array.Empty<string>());
        //await SendNotFoundAsync(ct);
    }
}
```
can you update this so it throws?

**Comment by Miatrix** [comment]
public class WeatherForecastEndpoint : EndpointWithoutRequest<string[]> works like you say however public class WeatherForecastEndpoint : EndpointWithoutRequest<string> will return Error: aborted with postman vs a 404. 

SendOkAsync("", ct) works, but is sending a 200 not a 404 like I want.
SendAsync("", 404, ct) also works but I'm trying to avoid sending content with a 404 if possible.

I tried public class WeatherForecastEndpoint : EndpointWithoutRequest<int> and it worked correctly so it has to be something specific with a string type.

**Comment by dj-nitehawk** [comment]
either of these would do then. (with latest beta that is)
```cs
await SendNotFoundAsync();
await SendAsync(null, 404);
```
you can me the TResponse `string?`
`EndpointWithoutRequest<string?>`
