### ISSUE TITLE
Cannot use AuthorizeAttribute on version 5.2

### ISSUE THREAD

**Issue by markchristianlacap** [FastEndpoints/FastEndpoints#281]
Building error when I upgrade to version 5.2
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'collection')
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at FastEndpoints.EndpointDefinition.Roles(String[] rolesNames)
   at FastEndpoints.EndpointExtensions.Configure(EndpointDefinition def, BaseEndpoint instance, Boolean implementsConfigure, Object[] epAttribs)
```

**Comment by dj-nitehawk** [comment]
fixed in `v5.2.0.2-beta`

thanks for reporting...
