### ISSUE TITLE
Interfaces and string return types swallow exceptions

### ISSUE THREAD

**Issue by KenBonny** [FastEndpoints/FastEndpoints#290]
During testing with exception flows, I noticed something curious. When the return type of an endpoint is either an interface or a string, the thrown exception is swallowed by a framework specific exception.

```
internal sealed class TestSomethingEndpoint : EndpointWithoutRequest<string>
{
    public override void Configure()
    {
        Get("/test");
    }

    public override Task<string> ExecuteAsync(CancellationToken ct)
    {
        throw new Exception("test exception");
        return Task.FromResult("message");
    }
}
```

Instead of the expected message _test exception_, I get the exception _Uninitialized Strings cannot be created._ with stack trace

```
   at System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(Type type)
   at System.Runtime.Serialization.FormatterServices.GetUninitializedObject(Type type)
   at FastEndpoints.Endpoint`2.InitResponseDTO()
   at FastEndpoints.Endpoint`2.get_Response()
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

A similar thing happens when I return an `interface`.

```
internal sealed class TestSomethingEndpoint : EndpointWithoutRequest<IEnumerable<string>>
{
    public override void Configure()
    {
        Get("/test/exception");
    }

    public override Task<IEnumerable<string>> ExecuteAsync(CancellationToken ct)
    {
        throw new Exception("test exception");
        return Task.FromResult(new[] { "message" }.AsEnumerable());
    }
}
```

Similar to the previous example, but this time the exception reads _Cannot create an instance of an interface._

```
   at System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(Type type)
   at System.Runtime.Serialization.FormatterServices.GetUninitializedObject(Type type)
   at FastEndpoints.Endpoint`2.InitResponseDTO()\r\n   at FastEndpoints.Endpoint`2.get_Response()
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

Also, as a note, for some reason there is no downcasting allowed in the return type. When I specify the return type as `IEnumerable<string>` and I return an `List<string>`, there is a compilation exception: _Cannot convert expression type 'System.Threading.Tasks.Task<System.Collections.Generic.List<string>>' to return type 'System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<string>>'_.  I need to cast it to the corresponding interface via `.AsEnumerable()`.

**Comment by KenBonny** [comment]
This is a bug in version 5.1.0, this is fixed in version 5.2.1.
