### ISSUE TITLE
[Bug][FE 5.3.0/.1] Roles Policy calls throw "AuthorizationPolicy named: 'epPolicy:<EndPointName>' was not found."

### ISSUE THREAD

**Issue by EelcoLos** [FastEndpoints/FastEndpoints#309]
## Expected Behavior
To have a rolecheck on a user, without `AuthorizationPolicy`.

## Actual Behavior
```json
{
    "status": "Internal Server Error!",
    "code": 500,
    "reason": "The AuthorizationPolicy named: 'epPolicy:Api.EndPoints.Folders.DeleteFolderEndpoint' was not found.",
    "note": "See application log for stack trace."
}
```

## Steps to Reproduce the Problem
1. As package, use FastEndpoints 5.3.1 
1. Write an Endpoint with requests using `FromClaim` and a non-`FromClaim`response (same parameters) and have the `Roles(<role>)` in Configure
1. Write the endpoint
1. Trigger the endpoint written with the proper role
1. You get the exception below
```csharp
public class DeleteFolderEndpoint : EndpointWithMapping<DeleteFolderEndpointRequest, EmptyResponse, DeleteFolderCommand>
	{
		private readonly DeleteFolderCommandHandler _commandHandler;

		public DeleteFolderEndpoint(DeleteFolderCommandHandler commandHandler)
		{
			_commandHandler = commandHandler;
		}
		public override void Configure()
		{
			Verbs(Http.DELETE);
			Routes("/folders/{FolderId}");
			Description(x =>
			{
				x.WithName("deleteFolder");
				x.Produces(StatusCodes.Status204NoContent);
				x.Produces(StatusCodes.Status403Forbidden);
				x.ProducesValidationProblem();
				x.ProducesProblemFE(StatusCodes.Status500InternalServerError);
			}, clearDefaults: true);

			Roles(Roles.ApplicatieBeheerRole);
		}

		public override async Task HandleAsync(DeleteFolderEndpointRequest req, CancellationToken ct)
		{
			var command = MapToEntity(req);

			var validationResults = await _commandHandler.HandleAsync(command);

			foreach (var error in validationResults.Errors) AddError(error.ErrorMessage);

			ThrowIfAnyErrors();

			await SendNoContentAsync(ct);
		}

		public override DeleteFolderCommand MapToEntity(DeleteFolderEndpointRequest request)
		{
			return new DeleteFolderCommand
			{
				FolderId = request.FolderId,
				CompanyId = request.CompanyId,
			};
		}
	}
```
```
FastEndpoints.ExceptionHandler[0]
      =================================
      HTTP: DELETE /api/folders/{FolderId}
      TYPE: InvalidOperationException
      REASON: The AuthorizationPolicy named: 'epPolicy: Api.EndPoints.Folders.DeleteFolderEndpoint' was not found.
      ---------------------------------
         at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authorizeData)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Api.Supports.ProxyForForge.InvokeAsync(HttpContext context, RequestDelegate next) in apps\api\Supports\ProxyForForge.cs:line 30
         at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Api.Supports.RoleCheckMiddleware.Invoke(HttpContext httpContext) in apps\api\Supports\RoleCheckMiddleware.cs:line 38
         at Program.<>c.<<<Main>$>b__0_3>d.MoveNext() in apps\api\Program.cs:line 59
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Shared.Startup.StrictSameSiteExternalAuthenticationMiddleware.Invoke(HttpContext ctx) in libs\shared\startup\StrictSameSiteExternalAuthenticationMiddleware.cs:line 51
         at Microsoft.Azure.AppConfiguration.AspNetCore.AzureAppConfigurationRefreshMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by EelcoLos** [comment]
note: this works in 5.2.1

**Comment by dj-nitehawk** [comment]
can't seem to replicate the issue. can you update the following program to replicate it pls?
```cs
using FastEndpoints;
using FastEndpoints.Security;
using FastEndpoints.Swagger;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddAuthenticationJWTBearer("_TokenSigningKey_");
builder.Services.AddFastEndpoints();
builder.Services.AddSwaggerDoc();

var app = builder.Build();
app.UseAuthentication();
app.UseAuthorization();
app.UseFastEndpoints();
app.UseOpenApi();
app.UseSwaggerUi3(c => c.ConfigureDefaults());
app.Run();

public class DeleteFolder : Endpoint<Request>
{
    public override void Configure()
    {
        Delete("/folder/{@id}", x => new { x.FolderId });
        Roles("Admin");
    }

    public override async Task HandleAsync(Request r, CancellationToken c)
    {
        await SendAsync("folder deleted!");
    }
}

public class Request
{
    public int FolderId { get; set; }
}

public class CreateToken : EndpointWithoutRequest
{
    public override void Configure()
    {
        Post("/token");
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken ct)
    {
        var jwtToken = JWTBearer.CreateToken(
            signingKey: "_TokenSigningKey_",
            roles: new[] { "Admin", "Management" });

        await SendAsync(jwtToken);
    }
}
```

**Comment by EelcoLos** [comment]
thnx for the feedback, I'll check and get back to you 👍

**Comment by EelcoLos** [comment]
i tried some solutions and was able to reduce it to

```cs

namespace test;

public class DeleteFolder : Endpoint<Request>
{
	public override void Configure()
	{
		Delete("/folder/{@id}", x => new { x.FolderId });
		Roles(Roles.ApplicatieBeheerRole);
	}

	public override async Task HandleAsync(Request r, CancellationToken c) => await SendAsync("folder deleted!");
}

public class Request
{
	public int FolderId { get; set; }
}
```

this returned the same
> 'The AuthorizationPolicy named: 'epPolicy:test.DeleteFolder' was not found.'

**Comment by dj-nitehawk** [comment]
nope... still can't reproduce it.
can you update the attached project and send back.
[Repro.zip](https://github.com/FastEndpoints/FastEndpoints/files/9908223/Repro.zip)

**Comment by EelcoLos** [comment]
I think I found the issue: the team at YARP changed their configuration documentation https://microsoft.github.io/reverse-proxy/articles/authn-authz.html#configuration. 

There, it's **now** defined as 

```cs
app.UseEndpoints(endpoints =>
    {
       endpoints.MapReverseProxy();
    });
```

where as before, the `MapReverseProxy()` was a top level registration (`app.MapReverseProxy()`).

**Comment by dj-nitehawk** [comment]
so all good then?

**Comment by EelcoLos** [comment]
we'll be running all kinds of regression tests to see if all things remain operational.
For now, yes, all is good. I'll reopen if need be.
