### ISSUE TITLE
Upgrading from 5.2.1 to 5.3.1 or 5.3.2 generates an Object reference not set to an instance of an object error

### ISSUE THREAD

**Issue by Miatrix** [FastEndpoints/FastEndpoints#317]
Here is part of my code:

```cs
        app.UseAuthentication();
        app.UseRouting();
        if (app.Environment.IsDevelopment())
        {
            app.UseOpenApi(); // Error happens here
            app.UseSwaggerUi3(s => s.ConfigureDefaults());
        }

        app.UseDefaultExceptionHandler();
        app.UseAuthorization();
        app.UseFastEndpoints(c =>
        {
            c.Endpoints.RoutePrefix = "api/v1";
        });`
```
Stacktrace:
```yaml
   at FastEndpoints.Swagger.ValidationSchemaProcessor..ctor()
   at FastEndpoints.Swagger.Extensions.EnableFastEndpoints(AspNetCoreOpenApiDocumentGeneratorSettings settings, Int32 tagIndex, Int32 minEndpointVersion, Int32 maxEndpointVersion, Boolean shortSchemaNames, Boolean removeEmptySchemas)
   at FastEndpoints.Swagger.Extensions.<>c__DisplayClass7_0.<AddSwaggerDoc>b__0(AspNetCoreOpenApiDocumentGeneratorSettings s)
   at Microsoft.Extensions.DependencyInjection.NSwagServiceCollectionExtensions.<>c__DisplayClass3_0.<AddSwaggerDocument>b__0(IServiceProvider services)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.NSwagApplicationBuilderExtensions.UseOpenApiWithApiExplorerCore(IApplicationBuilder app, Action`1 configure)
```

Any Ideas

**Comment by dj-nitehawk** [comment]
can you try moving this part:
```cs
if (app.Environment.IsDevelopment())
{
  app.UseOpenApi(); // Error happens here
  app.UseSwaggerUi3(s => s.ConfigureDefaults());
}
```
below the `app.UseFastEndpoints()` call pls...

**Comment by Miatrix** [comment]
That solved it.. I'm not sure why I had my UseFastEndpoints below it unless some example I found had it that way.  Thanks for the quick reply.

**Comment by dj-nitehawk** [comment]
i'll add an extra check for it in the next release.
when in doubt, check the samples on the doc site: https://fast-endpoints.com/docs/swagger-support#enable-swagger
