### ISSUE TITLE
OData Support

### ISSUE THREAD

**Issue by mkalinski93** [FastEndpoints/FastEndpoints#344]
Hey,

just wanted to get to know if we can use FastEndpoints with OData?
Any recommendations or documentations I can follow?

**Comment by dj-nitehawk** [comment]
unfortunately i have no exposure to odata. 
but if it can be used with asp.net minimal apis, it most likely will work with FE since it's just a wrapper around minimal apis. if you can point me in the direction of a odata example with minimal apis, i could try to translate that to FE.

**Comment by mkalinski93** [comment]
I am unsure OData can be used in minimal APIs yet (see [this issue](https://github.com/OData/AspNetCoreOData/issues/578). Maybe in the upcoming months, as Microsoft is pushing minimal APIs pretty consistently for the last dotnet releases.

**Comment by dj-nitehawk** [comment]
yeah looks like odata library doesn't yet have minimal api support. let's revisit this when they do. tc!

**Comment by dj-nitehawk** [comment]
@diegomodolo 
will you be able to point me in the direction of the docs/instructions how to use odata with minimal apis?
even better, if a small sample project could be attached here.
thanks!

**Comment by diegomodolo** [comment]
Hi @dj-nitehawk , I've created a small project showing the features.

It is here: 
https://github.com/[diegomodolo/MinimalAPIWithOData](https://github.com/diegomodolo/MinimalAPIWithOData

**Comment by dj-nitehawk** [comment]
okay soo... this is as far as i could get: [OData.zip](https://github.com/user-attachments/files/20061491/OData.zip)
basically, the endpoint is working but i could not figure out how to get the `.WithODataResult()` endpoint filter to play nice. so the result is not currently being wrapped in a `ODataResult`.
we might need some help from the odata guys to open up some of their internal types such as `ODataResult` to make this work.
maybe some of you can see a workaround...

**Comment by dj-nitehawk** [comment]
@rudiv 
> returning the actual result from the main FE invoker

yeah that's definitely not gonna fly. that's just extra unnecessary work in the hot path.
what if we implemented our own `IODataResult` and take matters into our own hands (copy their source initially of course)? 

---

in any case, i don't really see the point of FE "needing" to support odata. what do people hope to gain by using FE to define their odata endpoints? consitency with the rest of their endpoints maybe? creating "god endpoints" kinda seems like it doesn't fit well with the REPR idea.

**Comment by diegomodolo** [comment]
The way I see, there are two ways of using OData with endpoints: 

- Creating a single endpoint exposing all the entities and let the client query them all
- Creating a endpoint for each entity that gets ODataQueryOptions, apply it to the data and returns the result.

I agree with @dj-nitehawk when he says a god endpoint makes no sense for FE, but for the second way I think it would be a good fit.
For example, if I used AutoMapper, I could pass the ODataQueryOptions as a parameter of the request, the method would apply it (AutoMapper includes a extension method that applies the ODataQueryOptions to an IQueryable) and returns it in the response.

The only reason I don't use it like that is because I don't want to use AutoMapper in my projects.

**Comment by dj-nitehawk** [comment]
okay guys i have a working solution: [Solution.zip](https://github.com/user-attachments/files/20075937/Solution.zip)
will release a `FastEndpoints.OData` package as soon as i get a chance...
in the meantime, please check the solution and see if there's any edge cases it might miss...
in the final package, there will most likely be a new endpoint base class `ODataEndpoint<TEntity>` or if that doesn't pan out, maybe an extension method like `EnableOData()` for config or something. let's see...

**Comment by diegomodolo** [comment]
Thanks so much @dj-nitehawk , that's exactly what I was hoping for.
Great work!!

**Comment by dj-nitehawk** [comment]
alright... here you go: [FE-ODataSample.zip](https://github.com/user-attachments/files/20138734/FE-ODataSample.zip)
so, basically just:
```cs
sealed class CustomersEndpoint(AppDbContext db) : ODataEndpoint<Customer>
{
    protected override void Setup()
    {
        Get("/odata/customers");
        AllowAnonymous();
    }

    public override async Task<IQueryable> ExecuteAsync(ODataQueryOptions<Customer> req, CancellationToken ct)
    {
        await Task.CompletedTask;

        return req.ApplyTo(db.Customers);
    }
}
```
the `FastEndpoints.OData` pkg is currently referncing a nightly build. please someone ping me when they finalize the api and push out a stable release with the minimal apis support.

**Comment by yannhodiesne** [comment]
Not a stable release (yet), but `Microsoft.AspNetCore.OData` released the `9.4.0-preview` with minimal apis support  
Tried it on our project and it works with the current `FastEndpoints.OData`, apart from Swagger crashing with this error message when generating

<details>
  <summary>Swagger error logs</summary>

  ```
  fail: FastEndpoints.ExceptionHandler[4]
        =================================
  
  TYPE: InvalidOperationException
  REASON: Could not find the JSON path of a referenced schema: NJsonSchema.JsonSchema,NJsonSchema.JsonSchema,NJsonSchema.JsonSchema,NJsonSchema.JsonSchema,NJsonSchema.JsonSchema,NJsonSchema.JsonSchema,NJsonSchema.JsonSchema,NJsonSchema.JsonSchema,NJsonSchema.JsonSchema,NJsonSchema.JsonSchema,NJsonSchema.JsonSchema,NJsonSchema.JsonSchema,NJsonSchema.JsonSchema,NJsonSchema.JsonSchema,NJsonSchema.JsonSchema,NJsonSchema.JsonSchema,NJsonSchema.JsonSchema. Manually referenced schemas must be added to the 'Definitions' of a parent schema.
  ---------------------------------
     at NJsonSchema.JsonPathUtilities.GetJsonPaths(Object rootObject, IEnumerable`1 searchedObjects, IContractResolver contractResolver)
           at NJsonSchema.JsonSchemaReferenceUtilities.UpdateSchemaReferencePaths(Object rootObject, Boolean removeExternalReferences, IContractResolver contractResolver)
           at NJsonSchema.Infrastructure.JsonSchemaSerialization.ToJson(Object obj, SchemaType schemaType, IContractResolver contractResolver, Formatting formatting)
           at NSwag.OpenApiDocument.ToJson(SchemaType schemaType, Formatting formatting)
           at NSwag.OpenApiDocument.ToJson(SchemaType schemaType)
           at NSwag.OpenApiDocument.ToJson()
           at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
           at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
           at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
           at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
           at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
           at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
           at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
           at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
  ```
</details>

As always, thank you for your hard work @dj-nitehawk !

**Comment by diegomodolo** [comment]
Hi @dj-nitehawk , I've come across a situation and I would like to discuss it with you.
I have a scenario where I don't want to return the entity from the database, I want first to map it to a DTO.

Since I am using commands to execute the query, I would like to pass the ODataQueryOptions<Entity> to it, so I can filter the data, but as I won't be returning the entity itself, I need the response type of the Endpoint to be the DTO and not the entity.

I am willing to implement it, if possible, but I would like your opinion on how to approach this case.

**Comment by diegomodolo** [comment]
Thank you for the reply (by the way, I've made a contribution to the project, since you help us quite a lot).
Another change I've come across is that up until the last version I was using, the return of the ODataEndpoint was like this:

<img width="1154" height="96" alt="Image" src="https://github.com/user-attachments/assets/27bab96e-7270-433c-8b87-02748a88b447" />

But now it is just returning a list of entities, without the metadata.

Is this some type of configuration?
