### ISSUE TITLE
FastEndpoints was unable to find any endpoint declarations!

### ISSUE THREAD

**Issue by bogdandynamic** [FastEndpoints/FastEndpoints#362]
Hi. I've installed the FastEndpoints template for VisualStudio 2022, created a new project using
`dotnet new fastendpoints --name FastEndpointsTest`

Did not modify anything in the scaffolded project.
When running I get an InvalidOperationException with message "FastEndpoints was unable to find any endpoint declarations!".

Stack trace:
```
   at FastEndpoints.EndpointData.<>c__DisplayClass6_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at FastEndpoints.MainExtensions.MapFastEndpoints(IEndpointRouteBuilder app, Action`1 configAction)
   at FastEndpoints.MainExtensions.UseFastEndpoints(IApplicationBuilder app, Action`1 configAction)
   at Program.<<Main>$>d__0.MoveNext() in PATH\FastEndpointsTest\src\FastEndpointsTest\Program.cs:line 47
   at Program.<Main>(String[] args)
```

which points out to this
```
app.UseFastEndpoints(options =>
{
    options.Errors.ResponseBuilder = (errors, _, _) => errors.ToResponse();
    options.Errors.StatusCode = StatusCodes.Status422UnprocessableEntity;
    options.Serializer.Options.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
});
```

I was wondering what the problem could be.

**Comment by bogdandynamic** [comment]
Follow up: created another project via scaffolding (`dotnet new fastendpoints --name FastEndpointsTest2`) and this time everything works as expected. I diffed all files generated in both projects, no difference other than project name.
Don't know why first doesn't work and second works as expected.

Closing issue because could not reproduce problem.

**Comment by Nodios** [comment]
@bogdandynamic @dj-nitehawk I got the same issue - my solution name started with "FastEndpoints" and it failed to find endpoint declarations. I created new solution with different name, copied the code and it worked without a problem

**Comment by dj-nitehawk** [comment]
this behaviro is documented:

![screen-record-1679750921](https://user-images.githubusercontent.com/7043768/227720086-5ba5d0ce-82dd-4fd4-95a7-5660ea40b7a6.png)

**Comment by Nodios** [comment]
@dj-nitehawk yeah, I missed the docs, but I saw it in the source
