### ISSUE TITLE
Unable to parse using the built-in `IParsable<TSelf>` interface

### ISSUE THREAD

**Issue by KennethHoff** [FastEndpoints/FastEndpoints#385]
The following Parsing methods work:
![image](https://user-images.githubusercontent.com/17124533/219855849-b450acb8-ab3d-4adf-bd87-eb6651a4e288.png)

[The built-in `IParsable<TSelf>` ](https://learn.microsoft.com/en-us/dotnet/api/system.iparsable-1?view=net-7.0)has the following syntax - which does not work. I do not know what the `FormatProvider` does, but it's nullable so you can probably just set it to `default` :shrug: 
![image](https://user-images.githubusercontent.com/17124533/219855893-0612779f-06f2-4945-9dbf-07a345bc3448.png)
![image](https://user-images.githubusercontent.com/17124533/219855909-11dd9d2e-7c10-4172-9436-e7fd2a35216d.png)

Doing so throws this exception:
```
[11:40:45.632 ERR] An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method28(Closure, Object, Object)
   at FastEndpoints.RequestBinder`1.Bind(TRequest req, KeyValuePair`2 kvp, List`1 failures)
   at FastEndpoints.RequestBinder`1.BindRouteValues(TRequest req, RouteValueDictionary routeValues, List`1 failures)
   at FastEndpoints.RequestBinder`1.BindAsync(BinderContext ctx, CancellationToken cancellation)
   at FastEndpoints.Endpoint`2.BindRequestAsync(EndpointDefinition def, HttpContext ctx, List`1 failures, CancellationToken ct)
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```
which seems to crash around here in the `RequestBinder` class - the  `primaryProps.TryGetValue` returns `true` but sets `prop` to `null`
![image](https://user-images.githubusercontent.com/17124533/219856055-57570396-c365-4961-87cc-ac3c579e83c9.png)

(I'm using FastEndpoints 5.7.2)

**Comment by dj-nitehawk** [comment]
well, `IParsable` interface only available in .net 7.0 onwards. so FE doesn't have any knowledge of it nor any support for it.
FE excpects the standard `public static bool TryParse(string? input, out XYZ output)` signature as explained [here](https://fast-endpoints.com/docs/model-binding#supported-dto-property-types).

there's an easier alternative which doesn't require you to dirty up your classes with `TryParse` methods [here](https://fast-endpoints.com/docs/model-binding#custom-value-parsers).

**Comment by KennethHoff** [comment]
Does this mean you have no intention of supporting .Net 7, or it's new built-in `IParsable` standard (Given that you closed this as _completed_).

I use the same parsing logic for my JsonConverter in order to consolidate the logic into one place, so all I did was create my own non-standard interface - with the exact same methods, except without the nullable Provider parameter - which feels unnecessary.
![image](https://user-images.githubusercontent.com/17124533/219878944-fc2bf397-51ae-4fd0-a0d3-539a601d7d47.png)

**Comment by dj-nitehawk** [comment]
well... all the new minimal api features from .net 7.0 is already supported since the project does multi-targetting. but i'm intentionally keeping .net 7 specific code out of the source code until .net 7 becomes LTS.
however in this case, i figured out a way to get you `IParsable<T>` support without actually referencing the interface.
so go ahead and check out `v5.7.2.1-beta`.
as long as your class has the following method signature, it will now work:
```cs
public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out MyType result)
```
