### ISSUE TITLE
Method not found: 'FastEndpoints.EndpointData FastEndpoints.MainExtensions.get_Endpoints()'

### ISSUE THREAD

**Issue by VictorioBerra** [FastEndpoints/FastEndpoints#396]
FE 5.7.2.13-beta

Thanks for fixing that XUnit thing so quickly! I updated FE to the latest beta to test it out, and my app will no longer start.

Looks like this is coming from the Swagger stuff? Any ideas on where I can look?

Full Stack Trace:

```
System.MissingMethodException: Method not found: 'FastEndpoints.EndpointData FastEndpoints.MainExtensions.get_Endpoints()'.
   at FastEndpoints.Swagger.ValidationSchemaProcessor..ctor()
   at FastEndpoints.Swagger.Extensions.EnableFastEndpoints(AspNetCoreOpenApiDocumentGeneratorSettings settings, Int32 tagIndex, TagCase tagCase, Int32 minEndpointVersion, Int32 maxEndpointVersion, Boolean shortSchemaNames, Boolean removeEmptySchemas)
   at FastEndpoints.Swagger.Extensions.<>c__DisplayClass8_0.<AddSwaggerDoc>b__0(AspNetCoreOpenApiDocumentGeneratorSettings s)
   at Microsoft.Extensions.DependencyInjection.NSwagServiceCollectionExtensions.<>c__DisplayClass0_0.<AddOpenApiDocument>b__0(AspNetCoreOpenApiDocumentGeneratorSettings settings, IServiceProvider services)
   at Microsoft.Extensions.DependencyInjection.NSwagServiceCollectionExtensions.<>c__DisplayClass1_0.<AddOpenApiDocument>b__0(AspNetCoreOpenApiDocumentGeneratorSettings settings, IServiceProvider services)
   at Microsoft.Extensions.DependencyInjection.NSwagServiceCollectionExtensions.<>c__DisplayClass3_0.<AddSwaggerDocument>b__0(IServiceProvider services)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.NSwagApplicationBuilderExtensions.UseOpenApiWithApiExplorerCore(IApplicationBuilder app, Action`1 configure)
   at Microsoft.AspNetCore.Builder.NSwagApplicationBuilderExtensions.UseOpenApi(IApplicationBuilder app, Action`1 configure)
   at FastEndpoints.Swagger.Extensions.UseSwaggerGen(IApplicationBuilder app, Action`1 config, Action`1 uiConfig)
   at Program.<Main>$(String[] args) in Program.cs:line 95
```

**Comment by dj-nitehawk** [comment]
most likely you didn't upgrade to the beta of the `FastEndpoints.Swagger` pkg in your project.
check if that's the case...

**Comment by VictorioBerra** [comment]
That was the case 🤦‍♂️
