### ISSUE TITLE
There is a bug when AddSwaGGerDoc() is adjusted to SwaGGerDocument (Action<DocumentOptions>)

### ISSUE THREAD

**Issue by zfchai** [FastEndpoints/FastEndpoints#444]
There is a bug when `AddSwaGGerDoc()` is adjusted to `SwaGGerDocument (Action<DocumentOptions>)`!

-  `isSwaggerDoc = true; req.Args;`  => parameters can obtain values.
-  `isSwaggerDoc = false; req.Args;`  => parameter value is null.

MyWebApp.csproj

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
      <TargetFramework>net7.0</TargetFramework>
      <Nullable>enable</Nullable>
      <ImplicitUsings>enable</ImplicitUsings>
      <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FastEndpoints" Version="5.10.0.3-beta" />
      <PackageReference Include="FastEndpoints.Swagger" Version="5.10.0.3-beta" />
      <PackageReference Include="IGeekFan.AspNetCore.Knife4jUI" Version="0.0.13" />
    </ItemGroup>

</Project>
```

Please review the `MyWebApp` demo: 

- Program.cs

```csharp
global using FastEndpoints;
using FastEndpoints.Swagger;
using IGeekFan.AspNetCore.Knife4jUI;
using MyWebApp;

var builder = WebApplication.CreateBuilder();
builder.Services.AddFastEndpoints();

// attention ...
bool isSwaggerDoc = true;
if (isSwaggerDoc)
{
    // Obsolete("Use the SwaggerDocument() method!")
    builder.Services.AddSwaggerDoc(settings =>
    {
        settings.Title = "My API";
        settings.Version = "v1";
        settings.OperationProcessors.Add(new DefaultValueOperationProcessor());
    }, tagIndex: 0);

}
else
{
    // new bug! please refer to the `UserEndpoint` at the end.
    builder.Services.SwaggerDocument(o => {
        o.AutoTagPathSegmentIndex = 0;
        o.EnableGetRequestsWithBody = false;
        o.EnableJWTBearerAuth = true;
        o.FlattenSchema = false;
        o.ExcludeNonFastEndpoints = true;
        o.ShortSchemaNames = true;
        o.RemoveEmptyRequestSchema = false;
        o.DocumentSettings = s => {
            s.Title = "My API";
            s.Version = "v1";
            s.DocumentName = "DocumentName";
            s.Description = "Description";
            s.OperationProcessors.Add(new DefaultValueOperationProcessor());
            s.AllowReferencesWithProperties = true;
            s.RequireParametersWithoutDefault = true;
        };
    });
}

var app = builder.Build();

app.UseAuthorization();
app.UseFastEndpoints(c => 
{
    c.Endpoints.RoutePrefix = "api";
});

bool isSwagger = true;
if (isSwagger)
{
    app.UseSwaggerGen(); //add this
    // default swagger
    app.MapGet("/", async context => {
        context.Response.Headers.Add("Content-Type", "text/html");
        // await context.Response.WriteAsync("<a href=\"/swagger/index.html\">SWAGGER API</a><br/> ");
        context.Response.Redirect("/swagger/index.html");
        await context.Response.CompleteAsync();
    });
}
else
{
    // other Use
    app.UseOpenApi();
    app.UseKnife4UI(c => {
        c.RoutePrefix = "k4";
        c.SwaggerEndpoint("/v1/swagger.json", "v1 Docs");
    });
}

app.Run();
```

- DefaultValueOperationProcessor.cs

```csharp
using NSwag.Generation.Processors.Contexts;
using NSwag.Generation.Processors;
using NSwag;

namespace MyWebApp;

public class DefaultValueOperationProcessor : IOperationProcessor
{
    public bool Process(OperationProcessorContext context)
    {
        foreach (var parameter in context.OperationDescription.Operation.Parameters.Where(p => p.Kind == OpenApiParameterKind.Query))
        {
            if (parameter.Schema.Default is null)
            {
                parameter.Schema.Default = parameter.Schema.ActualTypeSchema.ToSampleJson();
            }
        }
        return true;
    }
}
```

- UserEndpoint.cs

```csharp
using System.ComponentModel;

namespace MyWebApp.Endpoints;

/// <summary>
/// UserEndpoint
/// </summary>
public class UserEndpoint : Endpoint<UserRequest<UserReqDto>, UserResponse<UserInfo>>
{
    public override void Configure()
    {
        Get("/user/query");
        AllowAnonymous();
        Options(x => x.WithTags("Users"));
    }

    public override async Task HandleAsync(UserRequest<UserReqDto> req, CancellationToken ct)
    {
        var userInfo = req.Args;  // notice：use the SwaggerDocument() method，Args value is null.
        var response = new UserResponse<UserInfo>
        {
            ResponseId = Guid.NewGuid().ToString(),
            Args = new UserInfo
            {
                IsOver18 = userInfo?.Age > 18,
                FullName = $"{userInfo?.FirstName}-{userInfo?.LastName}"
            }
        };

        await SendAsync(response);
    }
}

/// <summary>
/// UserRequest
/// </summary>
/// <typeparam name="TRequest"></typeparam>
public class UserRequest<TRequest> where TRequest : class
{
    /// <summary>
    /// RequestId
    /// </summary>
    public string RequestId { get; set; } = string.Empty;

    /// <summary>
    /// Args
    /// </summary>
    public TRequest? Args { get; set; }
}

/// <summary>
/// UserResponse
/// </summary>
/// <typeparam name="TResponse"></typeparam>
public class UserResponse<TResponse> where TResponse : class
{
    /// <summary>
    /// ResponseId
    /// </summary>
    public string ResponseId { get; set; } = string.Empty;

    /// <summary>
    /// Args
    /// </summary>
    public TResponse? Args { get; set; }
}

/// <summary>
/// UserReqDto
/// </summary>
public sealed class UserReqDto
{
    /// <summary>
    /// FirstName
    /// </summary>
    public string FirstName { get; set; } = string.Empty;

    /// <summary>
    /// LastName
    /// </summary>
    public string LastName { get; set; } = string.Empty;

    /// <summary>
    /// Age
    /// </summary>
    public int Age { get; set; }

    /// <summary>
    /// Features
    /// </summary>
    public UserFeatures Features { get; set; } = new();
}

/// <summary>
/// UserFeatures
/// </summary>
public class UserFeatures
{
    /// <summary>
    /// Weight
    /// </summary>
    public double Weight { get; set; }

    /// <summary>
    /// Height
    /// </summary>
    public double Height { get; set; }
}

/// <summary>
/// UserInfo
/// </summary>
public sealed class UserInfo
{
    /// <summary>
    /// FullName
    /// </summary>
    public string FullName { get; set; } = string.Empty;

    /// <summary>
    /// IsOver18
    /// </summary>
    public bool IsOver18 { get; set; }
}
```

**Comment by dj-nitehawk** [comment]
if you're using `s.AllowReferencesWithProperties = true;` then "try it out" will only work if you put `[FromQueryParams]` on the property. it works fine if you use like this:
```cs
var builder = WebApplication.CreateBuilder();
builder.Services
    .AddFastEndpoints()
    .SwaggerDocument(o =>
    {
        o.DocumentSettings = s =>
        {
            s.AllowReferencesWithProperties = false;
            s.OperationProcessors.Add(new DefaultValueOperationProcessor());
        };
        o.FlattenSchema = true;
        o.RemoveEmptyRequestSchema = true;
    });

var app = builder.Build();
app.UseFastEndpoints()
   .UseSwaggerGen();

app.Run();

public class DefaultValueOperationProcessor : IOperationProcessor
{
    public bool Process(OperationProcessorContext context)
    {
        foreach (var parameter in context.OperationDescription.Operation.Parameters.Where(p => p.Kind == OpenApiParameterKind.Query))
        {
            if (parameter.Schema.Default is null)
            {
                parameter.Schema.Default = parameter.Schema.ActualTypeSchema.ToSampleJson();
            }
        }
        return true;
    }
}

public class Arg
{
    public string Id { get; set; }
}

public class Request<T> where T : class
{
    public int MainId { get; set; }
    public T Args { get; set; }
}

public class GetRequest : Request<Arg> { }

public class GetEndpoint : Endpoint<GetRequest>
{
    public override void Configure()
    {
        Get("test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(GetRequest r, CancellationToken c)
    {
        await SendAsync(r);
    }
}

public class PostRequest : Request<Arg> { }

public class PostEndpoint : Endpoint<PostRequest>
{
    public override void Configure()
    {
        Post("test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(PostRequest r, CancellationToken c)
    {
        await SendAsync(r);
    }
}
```

**Comment by zfchai** [comment]
- SwaggerDocument

```csharp
builder.Services.SwaggerDocument(o => {
            o.AutoTagPathSegmentIndex = 0;
            o.EnableGetRequestsWithBody = false;
            o.EnableJWTBearerAuth = true;
            o.FlattenSchema = true; 
            o.ExcludeNonFastEndpoints = true;
            o.ShortSchemaNames = true;
            o.RemoveEmptyRequestSchema = true;
            o.DocumentSettings  = s => {
                s.Title = "Title";
                s.Version = "v1.0"
                s.DocumentName = "My API";
                s.Description = "My API";
                s.OperationProcessors.Add(new DefaultValueOperationProcessor());
                s.AllowReferencesWithProperties = false;
                s.RequireParametersWithoutDefault = true;
            };
        });
```

![image](https://github.com/FastEndpoints/FastEndpoints/assets/82487746/ec6117d5-ca02-46a5-8791-401b4a5ec820)

```csharp
==》2023-05-10 11:06:07.562 +08:00 Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware 17 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Could not find the JSON path of a referenced schema: Manually referenced schemas must be added to the 'Definitions' of a parent schema.
   at NJsonSchema.JsonPathUtilities.GetJsonPaths(Object rootObject, IEnumerable`1 searchedObjects, IContractResolver contractResolver)
   at NJsonSchema.JsonSchemaReferenceUtilities.UpdateSchemaReferencePaths(Object rootObject, Boolean removeExternalReferences, IContractResolver contractResolver)
   at NJsonSchema.Infrastructure.JsonSchemaSerialization.ToJson(Object obj, SchemaType schemaType, IContractResolver contractResolver, Formatting formatting)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[11:06:07 ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Could not find the JSON path of a referenced schema: Manually referenced schemas must be added to the 'Definitions' of a parent schema.
   at NJsonSchema.JsonPathUtilities.GetJsonPaths(Object rootObject, IEnumerable`1 searchedObjects, IContractResolver contractResolver)
   at NJsonSchema.JsonSchemaReferenceUtilities.UpdateSchemaReferencePaths(Object rootObject, Boolean removeExternalReferences, IContractResolver contractResolver)
   at NJsonSchema.Infrastructure.JsonSchemaSerialization.ToJson(Object obj, SchemaType schemaType, IContractResolver contractResolver, Formatting formatting)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by dj-nitehawk** [comment]
works fine: [project.zip](https://github.com/FastEndpoints/FastEndpoints/files/11437968/project.zip)

**Comment by zfchai** [comment]
Adjust the following configuration to operate normally: 

```csharp
o.FlattenSchema = false; 
o.RemoveEmptyRequestSchema = false;
...
s.AllowReferencesWithProperties = false;
```

**Comment by zfchai** [comment]
[project.zip](https://github.com/FastEndpoints/FastEndpoints/files/11437968/project.zip) 

The nuget package you are using

```xml
<PackageReference Include="FastEndpoints" Version="5.10.0" />
<PackageReference Include="FastEndpoints.Swagger" Version="5.10.0" />
```

The nuget package I am using

```xml
<PackageReference Include="FastEndpoints" Version="5.10.0.3-beta" />
<PackageReference Include="FastEndpoints.Swagger" Version="5.10.0.3-beta" />
<PackageReference Include="IGeekFan.AspNetCore.Knife4jUI" Version="0.0.13" />
```

### My doubts

Request<Arg>is a reference type, cannot GET and POST be used directly, why do we have to use different class inheritance to use it?

```csharp
Request<Arg> 
```

**Comment by dj-nitehawk** [comment]
my sample works even with `5.10.0.3-beta`: [project.zip](https://github.com/FastEndpoints/FastEndpoints/files/11442169/project.zip)

when you have inheritance hierarchies/ and or shared dto's you have to user schema flattenning. otherwise it doesn't work. it's the same with swashbuckle too. so either flatten the schema in swagger or switch to a vertical slice architecture that doesn't share any dtos.
