### ISSUE TITLE
System.InvalidOperationException: 'API Explorer not registered in DI.'

### ISSUE THREAD

**Issue by scottetass** [FastEndpoints/FastEndpoints#554]
I am using FastEndpoints for the first time and have followed through the documentation to create a very basic API.

Using the below code, an error is raised at startup:

> System.InvalidOperationException: 'API Explorer not registered in DI.'

If I comment out the _app.UseSwaggerGen();_ in the below Program.cs the app starts up and runs fine, albeit with no swagger support.

Program.cs
```
using FastEndpoints;
using FastEndpoints.Swagger;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddFastEndpoints();
builder.Services.AddSwaggerDocument();

var app = builder.Build();
app.UseFastEndpoints();
app.UseSwaggerGen();

app.Run();
```

Endpoint.cs
```
using FastEndpoints;

namespace MyWebApp
{
    public class MyResponse
    {
        public string FullName { get; set; }
        public bool IsOver18 { get; set; }
    }

    public class MyEndpoint : EndpointWithoutRequest<MyResponse>
    {
        public override void Configure()
        {
            Get("/api/user/create");
            AllowAnonymous();
        }

        public override async Task HandleAsync(CancellationToken ct)
        {
            await SendAsync(new()
            {
                FullName = "TEST",
                IsOver18 = true
            });
        }
    }
}
```

Stack Trace:
```
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware..ctor(RequestDelegate nextDelegate, IServiceProvider serviceProvider, String documentName, String path, OpenApiDocumentMiddlewareSettings settings)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.ReflectionMiddlewareBinder.CreateMiddleware(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__40.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<<StartAsync>b__15_1>d.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<ForeachService>d__18`1.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__15.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in C:\VSProjects\Test\MyWebApp\Program.cs:line 14
```

Project dependencies:
![image](https://github.com/FastEndpoints/FastEndpoints/assets/149555853/e20b3bd8-b2fc-4d12-a342-c5060ecbd77b)

**Comment by dj-nitehawk** [comment]
looks like you misread the documentation :-)

![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/40782df9-dcca-41d7-830b-2976601f1d1e)

**Comment by scottetass** [comment]
Oh, my apologies, how embarrassing ! Didn't mean to waste your time. Could have sworn I had checked it all.

**Comment by dj-nitehawk** [comment]
no worries at all...
the `.AddSwaggerDocument()` method is not from fastendpoints.
easy mistake to make ;-)
