### ISSUE TITLE
Unable to test the ValidationContext.ThrowError() on my user case

### ISSUE THREAD

**Issue by alva-lin** [FastEndpoints/FastEndpoints#586]
I referred to the [documentation](https://fast-endpoints.com/docs/validation#throwing-adding-errors-from-anywhere) on `throw error from anywhere` and called the `ValidationContext.Instance.ThrowError("some reason")` method in the business service. However, I encountered an obstacle when trying to write unit tests. An error occurred when obtaining the `ServiceResolver`.

Here is the core code section, the minimal sample code is in this [repository](https://github.com/alva-lin/MyIssue.NullServiceResolver)

```csharp
// business logic
public class Product
{
    public string Name { get; set; }
}

public class ProductService
{
    private readonly List<Product> _products = new();

    public bool AddProduct(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            // throw new ArgumentException("Product name cannot be empty", nameof(name));
            ValidationContext.Instance.ThrowError("Product name cannot be empty");
        }

        var product = new Product { Name = name };

        _products.Add(product);

        return true;
    }
}

// test code
public class ProductServiceUnitTest
{
    /// <summary>
    ///     https://fast-endpoints.com/docs/validation#throwing-adding-errors-from-anywhere
    ///     test <see cref="ValidationContext"/>, throw error from anywhere
    /// </summary>
    [Fact]
    public void TestAddWithEmptyName()
    {
        var service = new ProductService();

        Assert.ThrowsAny<ValidationFailureException>(() =>
        {
            service.AddProduct("");
        });
    }
}
```

The following is the error stack message from the test.

```log
Assert.Throws() Failure
Expected: typeof(FastEndpoints.ValidationFailureException)
Actual:   typeof(System.InvalidOperationException): Service resolver is null! Have you done the unit test setup correctly?
   at FastEndpoints.Config.get_ServiceResolver()
   at FastEndpoints.ValidationContext..ctor()
   at FastEndpoints.ValidationContext.get_Instance()
   at ProductService.AddProduct(String name) in E:\repos\MyFastEndpoint.NullServiceResolver\MyWebApp\Program.cs:line 32
   at MyTestProject.ProductServiceUnitTest.<>c__DisplayClass1_0.<TestAddWithEmptyName>b__0() in E:\repos\MyFastEndpoint.NullServiceResolver\MyTestProject\ProductServiceUnitTest.cs:line 29
```

I found the location of the source code for the part that reported the error

https://github.com/FastEndpoints/FastEndpoints/blob/cd364c58f8e081cd7d7e9bfbb78b78cf7639e397/Src/Library/Validation/ValidationContext.cs#L16-L19

https://github.com/FastEndpoints/FastEndpoints/blob/cd364c58f8e081cd7d7e9bfbb78b78cf7639e397/Src/Library/Config/Config.cs#L15-L21

---

Since I'm also new to the FastEndpoints library, as well as learning how to write unit tests, I don't know what to do for now. Do I need to mock `Cfg.ServiceResolver` in advance? Or should I not use `ValidationContext` in such scenarios, but just use Throw Error.

**Comment by dj-nitehawk** [comment]
`ValidationContext` is not a prime candidate for unit tests, however you can make it work like this:
```cs
[Fact]
public void TestAdd()
{
    Factory.RegisterTestServices(s => { }); //add this

    var service = new ProductService();

    var result = service.AddProduct("test name");

    Assert.True(result);
}

[Fact]
public void TestAddWithEmptyName()
{
    Factory.RegisterTestServices(s => { }); //add this

    var service = new ProductService();

    Assert.Throws<ValidationFailureException>(
        () =>
        {
            service.AddProduct("");
        });
}
```
