### ISSUE TITLE
After updating to latest release version (v5.22 Release) - Request DTOs without any publicly accessible properties are not supported

### ISSUE THREAD

**Issue by ImadAbukhadra** [FastEndpoints/FastEndpoints#599]
Hello, Thank you for your excellent project!

I have several fast endpoints that accept DTOs, but there are no publicly accessible properties, therefore I utilized this way to adjust the DTO as needed. However, everything was operating properly until I updated the fast endpoint to the current version. Then I faced a runtime error that affected swagger rendering as well.

I'm not sure if this issue belong to FastEndPoints nor Nswag. However,  

**The stack trace for the error is as follows:**

 Request DTOs without any publicly accessible properties are not supported. Offending Endpoint: [IntegrationServices.RestServices.FastEndPoints.CancelIrisCapture] Offending DTO type: [DataContracts.RequestsDtos.Biometrics.Iris.CancelIrisCaptureRequestDto]
System.NotSupportedException: Request DTOs without any publicly accessible properties are not supported. Offending Endpoint: [IntegrationServices.RestServices.FastEndPoints.CancelIrisCapture] Offending DTO type: [DataContracts.RequestsDtos.Biometrics.Iris.CancelIrisCaptureRequestDto]
   at FastEndpoints.Swagger.OperationProcessor.Process(OperationProcessorContext ctx)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.RunOperationProcessors(OpenApiDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, OpenApiOperationDescription operationDescription, List`1 allOperations, OpenApiDocumentGenerator generator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateApiGroups(OpenApiDocumentGenerator generator, OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.OutputCaching.OutputCacheMiddleware.<>c__DisplayClass11_0.<<InvokeAwaited>g__ExecuteResponseAsync|0>d.MoveNext()
--- End of stack trace from previous location ---

Thank you in advance for your support!

**Comment by dj-nitehawk** [comment]
fastendpoints never supported binding to request dtos without public properties. the new version just started to warn users properly. you can do the following for endpoints that has a blank request dto:
```cs
sealed class MyEndpoint : Endpoint<EmptyRequest,ResponseDto>

// or use the endpoint variation

sealed class MyEndpoint : EndpointWithoutRequest<ResponseDto>
```
