### ISSUE TITLE
Nullpointer using ValidationFailure without PropertyName using ProblemDetails

### ISSUE THREAD

**Issue by Maskoe** [FastEndpoints/FastEndpoints#618]
Sample
```cs
using FastEndpoints;
using FluentValidation.Results;

var bld = WebApplication.CreateBuilder();
bld.Services.AddFastEndpoints();

var app = bld.Build();
app.UseFastEndpoints(x => { x.Errors.UseProblemDetails(); });
app.Run();

public class MyEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("/api/vali");
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken ct)
    {
        ThrowError(new ValidationFailure { ErrorMessage = "err", }); // crashes
        // ThrowError("err"); // works
        // ThrowError(new ValidationFailure()); // crashes
        // ThrowError(new ValidationFailure { PropertyName = "prop", }); // works
        // ThrowError(new ValidationFailure { PropertyName = "prop", ErrorMessage = "err"}); // works  
    }
}
```

Expectation:
`ThrowError(new ValidationFailure { ErrorMessage = "err" });` has the same behaviour as `ThrowError("err");`.
PropertyName/name just gets set to "generalErrors".

Stacktrace:
```cs
System.NullReferenceException: Object reference not set to an instance of an object.
         at FastEndpoints.ProblemDetails.Error.Comparer.GetHashCode(Error obj)
         at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
         at System.Collections.Generic.HashSet`1.Add(T item)
         at FastEndpoints.ProblemDetails.Initialize(IReadOnlyList`1 failures, String instance, String traceId, Int32 statusCode)
         at FastEndpoints.ProblemDetails..ctor(IReadOnlyList`1 failures, String instance, String traceId, Int32 statusCode)
         at FastEndpoints.ProblemDetails.<>c.<.cctor>b__47_0(List`1 failures, HttpContext ctx, Int32 statusCode)
         at FastEndpoints.HttpResponseExtensions.SendErrorsAsync(HttpResponse rsp, List`1 failures, Int32 statusCode, JsonSerializerContext jsonSerializerContext, CancellationToken cancellation)
         at FastEndpoints.Endpoint`2.SendErrorsAsync(Int32 statusCode, CancellationToken cancellation)
         at FastEndpoints.Endpoint`2.<>c__DisplayClass0_0.<<ExecAsync>g__ValidationFailed|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
         at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by dj-nitehawk** [comment]
thanks for reporting...
fixed in `v5.22.0.15-beta`
