### ISSUE TITLE
How to fix Service resolver is null for CommandHandlers

### ISSUE THREAD

**Issue by d4rkm0nkey** [FastEndpoints/FastEndpoints#632]
I have the following Unit test in NUnit:
```csharp
private Mock<IMyClient> ClientMock { get; set; }
[SetUp]
public new async Task SetUp()
{
    ClientMock = new Mock<IMyClient>();
}

[Test]
public async Task MyTest()
{
    await using var dbContext = new MyDbContext(ConnectionString);
    var repository = new MyRepository(dbContext);
    var handler = new MyHandler(repository, ClientMock.Object, Logger.None);

    var command = new MyCommand
    {
        MyParameter = 1
    };

    var result = await handler.ExecuteAsync(command, CancellationToken.None);
    ...
```
I get this error, when I run the test:
    
```console
System.InvalidOperationException : Service resolver is null! Have you done the unit test setup correctly?
   at FastEndpoints.Config.get_ServiceResolver()
   at FastEndpoints.ValidationContext..ctor()
   at FastEndpoints.ValidationContext`1..ctor()
   at FastEndpoints.CommandHandlerBase`1..ctor()
   at FastEndpoints.CommandHandler`2..ctor()
```
 I have the exact same test setup for a different command handler and it works.
 I found these issues: #582 and #382, but they only explain how to do it with endpoints.

**Comment by dj-nitehawk** [comment]
try placing the following call inside the test method on the first line before anything else gets called:
```cs
Factory.RegisterTestServices(s => { });
```
if that doesn't work, i'm going to need a standalone, debuggable repro project.

**Comment by d4rkm0nkey** [comment]
It works! Thank you!
