### ISSUE TITLE
Get request params

### ISSUE THREAD

**Issue by maurosampietro** [FastEndpoints/FastEndpoints#662]
Hi,
I'm using 5.24.0 dlls.

From swagger executing get endpoints with more than 0 query params return this error:

TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.

I notice swagger don't generate fields for query params but a generic 'post like' text area.

```
public class GetOperatorEndpoint : Endpoint<GetOperatorRequest, GetOperatorResponse>
{
    private readonly IDbContextFactory<DelcoNetContext> _dbContextFactory;

    public GetOperatorEndpoint( IDbContextFactory<DelcoNetContext> dbContextFactory )
    {
        _dbContextFactory = dbContextFactory;
    }

    public override void Configure()
    {
        Get( "/Operators/{Badge}" );
        AllowAnonymous();
    }

    public override async System.Threading.Tasks.Task HandleAsync( GetOperatorRequest req, CancellationToken ct )
    {
        using DelcoNetContext dbContext = await _dbContextFactory.CreateDbContextAsync( ct );

        var operators = await dbContext.Operators
            .FromSql( $"EXECUTE OperatorSelectByBadge @Badge = {req.Badge}" )
            .ToListAsync( ct );

        //ignore mutliple operators with same badge (should not happen)
        var operatorEntity = operators?.FirstOrDefault() ?? new Persistence.Database.Entities.Operator();
        OperatorData operatorData = null;
        if( operatorEntity?.Data != null )
            operatorData = System.Text.Json.JsonSerializer.Deserialize<OperatorData>( operatorEntity?.Data );

        var response = new GetOperatorResponse() { Operator = operatorData };
        await SendOkAsync( response, ct );
    }
}

public class GetOperatorRequest
{
    [QueryParam]
    public string Badge { get; set; } = default!;
}

```

![image](https://github.com/FastEndpoints/FastEndpoints/assets/15122144/6a2f2ba7-cd12-4766-9686-d6a64fbab6ff)

**Comment by maurosampietro** [comment]
Ok then I guess i need to EnableFastEndpoints from AddSwaggerDocument? Documentation seems to be behind the actual lib. Anyway... i get an exception there.

```c#
builder.Services
    .AddSwaggerDocument( config =>
    {
        config.EnableFastEndpoints( options => { } );
    } )    
```


 Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidCastException: Unable to cast object of type 'NJsonSchema.Generation.SystemTextJsonSchemaGeneratorSettings' to type 'NJsonSchema.NewtonsoftJson.Generation.NewtonsoftJsonSchemaGeneratorSettings'.
         at FastEndpoints.Swagger.OperationProcessor.Process(OperationProcessorContext ctx)
         at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.RunOperationProcessors(OpenApiDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, OpenApiOperationDescription operationDescription, List`1 allOperations, OpenApiDocumentGenerator generator, OpenApiSchemaResolver schemaResolver)
         at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
         at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateApiGroups(OpenApiDocumentGenerator generator, OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
         at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by dj-nitehawk** [comment]
looks like you're not following the docs correctly. please read carefully here: https://fast-endpoints.com/docs/swagger-support#enable-swagger

hint: we don't use `AddSwaggerDocument`

this is the way:
![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/853d3168-499d-4c57-bafd-a60e8117284a)

**Comment by maurosampietro** [comment]
That was it!
Thank you for your time.
I migrated from eralier version of fastendpoints and this happened unfortunately...

**Comment by dj-nitehawk** [comment]
glad to be of service :-)
