### ISSUE TITLE
[Bug] New swagger extension version throws an exception on document generation

### ISSUE THREAD

**Issue by vpetrusevici** [FastEndpoints/FastEndpoints#686]
Hi!
When I have endpoints with route validation like this one /{cardId:int:min(1)}/pan
i have this exception on openapi document generation
```
System.ArgumentOutOfRangeException: length ('-1') must be a non-negative value. (Parameter 'length')
Actual value was -1.
   at System.ArgumentOutOfRangeException.ThrowNegative[T](T value, String paramName)
   at System.ArgumentOutOfRangeException.ThrowIfNegative[T](T value, String paramName)
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FastEndpoints.Swagger.OperationProcessor.ParamCreationContext.<>c.<.ctor>b__13_1(String s)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.Dictionary`2.AddRange(IEnumerable`1 enumerable)
   at FastEndpoints.Swagger.OperationProcessor.ParamCreationContext..ctor(OperationProcessorContext opCtx, DocumentOptions docOpts, JsonSerializer serializer, Dictionary`2 descriptions, String operationPath)
   at FastEndpoints.Swagger.OperationProcessor.Process(OperationProcessorContext ctx)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.RunOperationProcessors(OpenApiDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, OpenApiOperationDescription operationDescription, List`1 allOperations, OpenApiDocumentGenerator generator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateApiGroups(OpenApiDocumentGenerator generator, OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
```

it worked in previous version.

Also it's still working for endpoints like without additional validation like /{cardId:int}/pan

I'm pretty sure it's related to these changes https://github.com/FastEndpoints/FastEndpoints/commit/2155df2b2b5e5c3d1a7dd1efd462bf2e7c2fad2e#diff-5bfa5d5552997c0e3ad420a2ad67c42a64e6b897aaf9bec14b05a7937980d3ceR678 rows 688, 689

**Comment by KateyBee** [comment]
Thanks for reporting.
Fixed in `vv5.25.0.8-beta`
