### ISSUE TITLE
.net 9.0 use SwaggerDocument() Error

### ISSUE THREAD

**Issue by xgaxpp** [FastEndpoints/FastEndpoints#799]
.net 9.0 project use SwaggerDocument() error

```
using FastEndpoints;
using FastEndpoints.Swagger;
using Serilog;
using Serilog.Extensions.Logging;
using Web.Configurations;

var builder = WebApplication.CreateBuilder(args);
var logger = Log.Logger = new LoggerConfiguration().Enrich.FromLogContext().WriteTo.Console().CreateLogger();

logger.Information("Starting web host");

builder.AddLoggerConfigs();

var appLogger = new SerilogLoggerFactory(logger).CreateLogger<Program>();


builder.Services.AddFastEndpoints().SwaggerDocument();

var app = builder.Build();

app.UseFastEndpoints().UseSwaggerGen(); // Includes AddFileServer and static files middleware

await app.UseAppMiddleware();

app.Run();

// Make the implicit Program.cs class public, so integration tests can reference the correct assembly for host building
public partial class Program {}

```

error:

```
Unhandled exception. System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.MemoryMarshal' from assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at <PrivateImplementationDetails>.InlineArrayAsSpan[TBuffer,TElement](TBuffer& buffer, Int32 length)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at FastEndpoints.ServiceResolver.CreateSingleton(Type type)
   at FastEndpoints.Swagger.Extensions.EnableFastEndpoints(AspNetCoreOpenApiDocumentGeneratorSettings settings, DocumentOptions opts, IServiceProvider serviceProvider)
   at FastEndpoints.Swagger.Extensions.<>c__DisplayClass4_0.<SwaggerDocument>b__0(AspNetCoreOpenApiDocumentGeneratorSettings genSettings, IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.NSwagServiceCollectionExtensions.<>c__DisplayClass1_0.<AddOpenApiDocument>b__0(AspNetCoreOpenApiDocumentGeneratorSettings settings, IServiceProvider services)
   at Microsoft.Extensions.DependencyInjection.NSwagServiceCollectionExtensions.<>c__DisplayClass3_0.<AddSwaggerDocument>b__0(IServiceProvider services)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.NSwagApplicationBuilderExtensions.UseOpenApi(IApplicationBuilder app, Action`1 configure)
   at FastEndpoints.Swagger.Extensions.UseSwaggerGen(IApplicationBuilder app, Action`1 config, Action`1 uiConfig)
   at Program.<Main>$(String[] args) in D:\Workspapce\Dumbo.CleanArchitecture\src\Web\Program.cs:line 21
   at Program.<Main>(String[] args)

```

**Comment by dj-nitehawk** [comment]
i'm unable to reproduce this.
can you attach a minimalistic repro project with just one endpoint so i can debug?
thanks!

**Comment by xgaxpp** [comment]
hi, project there https://github.com/xgaxpp/WebApplication1

**Comment by xgaxpp** [comment]
hi, @dj-nitehawk , project here https://github.com/xgaxpp/WebApplication1
When I was replicating it, I realized that it might not be fastendpoint itself. The error will not be reported until other packages are added. But let me show you the project.
It starts correctly in MacOS. But swagger json is not generated


System: windows 23H2 22631.4317

**Comment by dj-nitehawk** [comment]
cloned your gh repo. works just fine: https://streamable.com/oig2jr

**Comment by xgaxpp** [comment]
Thank you for your help. That may be due to my local circumstances. I'm looking into it.
