### ISSUE TITLE
One Time Error during Swagger Validation Schema Processing of ChildValidatorAdaptor 

### ISSUE THREAD

**Issue by PeterMarinov** [FastEndpoints/FastEndpoints#827]
## Summary
The Swagger's integration of FluentValidation throws an exception during the execution of `ValidationSchemaProcessor.Process`  method when a FastEndpoint's  Request's Validator class uses the `Include` pattern to reuse validaiton logic  https://docs.fluentvalidation.net/en/latest/including-rules.html?highlight=include 

## Steps to Reproduce

1.  Create and endpoint, which uses `Include()` & inheritance in the Request validator. The following endpoint/request/validation code is sufficient for the steps:

```c#

using FluentValidation;

namespace TestCases.ReusingValidationTest;

public class PagedRequestValidator : AbstractValidator<IPagedRequest>
{
    public PagedRequestValidator()
    {
        RuleFor(x => x.Page)
           .GreaterThan(0)
           .When(x => x.Page.HasValue);

        RuleFor(x => x.PageSize)
            .GreaterThan(0)
            .When(x => x.PageSize.HasValue);
    }

    private object RuleFor(Func<object, object> value)
    {
        throw new NotImplementedException();
    }

}


public class RequestValidator : Validator<Request>
{
    /// <summary>
    /// Default constructor
    /// </summary>
    public RequestValidator()
    {
        Include(new PagedRequestValidator());

        RuleFor(x => x.SearchTerm)
        .NotEmpty();

        var logger = Resolve<ILogger<RequestValidator>>();
        logger.LogError("including rules from RequestValidator works!");
    }
}

public interface IPagedRequest
{
    int? Page { get; set; }

    int? PageSize { get; set; }
}

public class Request : IPagedRequest
{
    public string SearchTerm { get; set; }

    public int? Page { get; set; }

    public int? PageSize { get; set; }
}

public class ReusingValidationEndpoint : Endpoint<Request>
{
    public override void Configure()
    {
        Get("/test-cases/reusing-validation-test");
        AllowAnonymous();
    }

    public override Task HandleAsync(Request req, CancellationToken c)
    {
        return Task.CompletedTask;
    }
}
```

3. Build your project and run locally
4. Go to [http://localhost:5001/swagger/index.html](http://localhost:5001/swagger/index.html)

### Expected

Swagger documentation page loads with no issues in the Debug Console 

### Actual

Swagger documentation page loads, but the following exception is thrown and registered into the Debug console

>[!NOTE]
> The validation works as expected for each request using the FastEndpoints validation pipeline. It's just that that initial request for Swagger to parse the validation schema. Here is the detailed stack trace:

```bash
        FastEndpoints.Swagger.ValidationSchemaProcessor[0]
      Exception while processing TestCases.ReusingValidationTest.RequestValidator
      System.InvalidOperationException: Multiple constructors accepting all given argument types have been found in type 'FluentValidation.ValidationContext`1[TestCases.ReusingValidationTest.Request]'. There should only be one applicable constructor.
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.TryFindMatchingConstructor(Type instanceType, Type[] argumentTypes, ConstructorInfo& matchingConstructor, Nullable`1[]& parameterMap)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.FindApplicableConstructor(Type instanceType, Type[] argumentTypes, ConstructorInfoEx[] constructors, ConstructorInfo& matchingConstructor, Nullable`1[]& matchingParameterMap)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactoryInternal(Type instanceType, Type[] argumentTypes, ParameterExpression& provider, ParameterExpression& argumentArray, Expression& factoryExpressionBody)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory(Type instanceType, Type[] argumentTypes)
         at FastEndpoints.ServiceResolver.<CreateInstance>g__FactoryInitializer|6_0(Type t) in /Users/some_user/Code/FastEndpoints/Src/Library/ServiceResolver/ServiceResolver.cs:line 26
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at FastEndpoints.ServiceResolver.CreateInstance(Type type, IServiceProvider serviceProvider) in /Users/some_user/Code/FastEndpoints/Src/Library/ServiceResolver/ServiceResolver.cs:line 18
         at FastEndpoints.Swagger.ValidationSchemaProcessor.ApplyRulesFromIncludedValidators(JsonSchema schema, IValidator validator, IServiceProvider services) in /Users/some_user/Code/FastEndpoints/Src/Swagger/ValidationSchemaProcessor.cs:line 136
         at FastEndpoints.Swagger.ValidationSchemaProcessor.ApplyValidator(JsonSchema schema, IValidator validator, String propertyPrefix, IServiceProvider services) in /Users/some_user/Code/FastEndpoints/Src/Swagger/ValidationSchemaProcessor.cs:line 96
         at FastEndpoints.Swagger.ValidationSchemaProcessor.Process(SchemaProcessorContext context) in /Users/some_user/Code/FastEndpoints/Src/Swagger/ValidationSchemaProcessor.cs:line 79
FastEndpoints.Swagger.ValidationSchemaProcessor: Error: Exception while processing TestCases.ReusingValidationTest.RequestValidator
```

### Details

* Tested on two versions .NET 8 and .NET 9.0.10 and happens on both
* FastEndpoints v5.31
* Mac OS - 15.1 (24B83) Sequoia - M1 Max

 It looks that this goes to the `ServiceResolver.CreateInstance` invoked from the `ApplyRulesFromIncludedValidators`. I  tried debugging once to pin poin how this can be solved, but did now have any luck. 
 
**Severity** -  `low`. First of all, this is one time triggered during accessing the swagger docs - http://localhost:5001/swagger/index.html. Second, with .NET 9 and the replacement of Swagger with `Microsoft.AspNetCore.OpenApi` investing into fixing this issue might make not much sense.

Before I attempt further, I wanted to post the issue to see if my code might be the problem. Hope the sample will help. Thanks!

**Comment by dj-nitehawk** [comment]
thanks for reporting.
fixed in `v5.31.0.11-beta`

**Comment by PeterMarinov** [comment]
Great, thank you for fixing this. I can confirm it's working now. 🙇 

Saw the fix. Makes total sense now that I see it. I wanted to mess around with the factory logic for the validation context myself, but didn't know the system well enough to figure it out.

Awesome product!

P.S. You might want to remove this line in one of the next version ` var xxx = adapterMethod.GetParameters();` - https://github.com/FastEndpoints/FastEndpoints/commit/177c6ea36478429dfe6abd67e33994166e3bb57d#diff-0a51502db66c83c5ce88d93aa7a627fce4a024132ccbb4d4541abd773480234dR137

**Comment by dj-nitehawk** [comment]
thank you... totally forgot remove that line ;-)
also added a test case which should prevent this from ever popping up again.
have a great day!
